var theCoreTerms = ['A (basket|package|raft|range|sense|series) of','A fine art','Affordable','Any time soon','any way, shape or form','At the end of the day','At this moment in time','Beggars Belief','beleaguered','Big Ask','Body blow','catastroph(e|ic)','Celebrat(es*|ing) diversity','Celebrity','Chaos','Community','Crowd-*sourc(e|ing)','Deafening silence','Deliverables*','Economy, stupid','elephant in the room','Empower','Enough already','Epic Fail','Equality','Exponentially','Febrile','Fit for Purpose','forward policy','Game-chang(er|ing)','gamely','Going forward','Good Election to Lose','Guilty as charged','Guns blazing','Hard(-| |)working families','Hearts and minds','Hodge-podge','hysterical','Iconic','Is it just me, or','knee-jerk','Learning curve','Let’s be clear','Lifestyle','Makeover','makes no mention','meaning(ful|less)','Name and Shame','no-brainer','On a daily basis','Organically','Out of the box','Paradigm','Parameters*','Perfect Storm','Political hot potato','Political Journey','Pot, Kettle','Progressive','Progressives*','rais(es*|ing) awareness','read(ing)*(| \w*) the Riot Act','reared its(| ugly) head','scandalous','Scrap heap','(Sea|Step)(-| )change','Seal the Deal','Significant','Sleaze','Stark contrast','the hallmarks of','The(| simple) fact(| of the matter) is','The truth is','[^\'\"]The \w+ Delusion[^\'\"]','touch base','Vibrant','vulnerable moment','wanton','Way (beyond|more)','Who knew?','wrong-headed'];

var theExtraTerms = ['Arguably','Chutzpah','Clearly','Crazy','Creeping privati[s|z]ation','Cynica(l|lly)','Decen(t|cy)','Defend(ing)* the indefensible','Delusional','Devastating','Disgrace(ful)*','Disgusting','Distort(ed|ing)','Dodgy','Endanger','Fairness','Half-baked','Ideological','Ideologues*','ill-(conceived|considered|informed)','Immoral','Imperialis[m|t]','Inclusive','Incredibly','Inevitable','Inexorable','Insignificant','Irrationa(l|lly)','Lamented','Laughable','Laz(y|iness)','Leading (blogger|reason)s*','Level killing-field','Ludicrous','Meaning(ful|less)','Nonsensical','Out of touch','Parasites*','Pithy','Prescient','Prostrated','Reactionary','Regurgitat(e|ing)','Reframe','Regressive','Robust','Self-(hatred|indulgent|satisfied)','Shameless(ly)*','Slash(ed)*','Spin','Substan(ce|tial)','Sycophantic','Thought(ful|less)','Uncritical','Undeniabl(e|y)','Unfairness','Unforgettable','Unintelligent','Unsurprisingly','Unthinking','Vital','Vulnerable groups*','Vultures*','Willful ignorance'];

$(function() {
    $('body').highlight( theCoreTerms.join('|'), 'highlightCore');
    $('body').highlight( theExtraTerms.join('|'), 'highlightExtra');
//  $('body').highlight( '\b' + thePattern + '\b');
//  $("#remove").click(function() {$("#row").removeHighlight();});
});